#ifndef BOOKKEEPERLIB_GLOBAL_H
#define BOOKKEEPERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BOOKKEEPERLIB_LIBRARY)
#define BOOKKEEPERLIB_EXPORT Q_DECL_EXPORT
#else
#define BOOKKEEPERLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // BOOKKEEPERLIB_GLOBAL_H
